### ISSUE TITLE
你好，大神，我把项目导入了androidstudio ，请问CPP下面的Shared Library是从哪儿来的？ 

### ISSUE THREAD

**Issue by mankind-evolve** [coopsrc/FFPlayerDemo#1]
百度了好多资料  百思不得其解，特来诚心请教

**Comment by Alexmego** [comment]
这是ffmpeg build 脚本生成的动态库.看到README中关于ffmpeg 编译环境的介绍了吧?就是通过这个脚本生成的.

**Comment by coopsrc** [comment]
lib主要是下载ffmpeg源码通过脚步编译，然后集成到项目中。这篇博客中有说明。
https://www.jianshu.com/p/0a7f3175c1b9
